///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryProductsDataData {
/*
{
  "id": 66,
  "price": 39.99,
  "old_price": 39.99,
  "discount": 0,
  "image": "https://student.valuxapps.com/storage/uploads/products/1620253816SgPr3.1.jpg",
  "name": "Black Earloop Face Mask - 50 Pcs in box",
  "description": "Type : Fold-Flat Dust Masks\r\nBrand : ARW\r\nPackage thickness: 12.4 centimeters\r\nPackage weight in KGs238 grams\r\nColor Family : Multi Color\r\nSub Type : Dust Masks\r\nSterilized fabric\r\nHypoallergenic\r\nFilter",
  "images": [
    "https://student.valuxapps.com/storage/uploads/products/1620253816FGOZo.1.jpg"
  ],
  "in_favorites": false,
  "in_cart": false
}
*/

  int? id;
  double? price;
  double? oldPrice;
  int? discount;
  String? image;
  String? name;
  String? description;
  List<String?>? images;
  bool? inFavorites;
  bool? inCart;

  CategoryProductsDataData({
    this.id,
    this.price,
    this.oldPrice,
    this.discount,
    this.image,
    this.name,
    this.description,
    this.images,
    this.inFavorites,
    this.inCart,
  });
  CategoryProductsDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    price = json["price"]?.toDouble();
    oldPrice = json["old_price"]?.toDouble();
    discount = json["discount"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    if (json["images"] != null) {
      final v = json["images"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
    inFavorites = json["in_favorites"];
    inCart = json["in_cart"];
  }
}

class CategoryProductsData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 66,
      "price": 39.99,
      "old_price": 39.99,
      "discount": 0,
      "image": "https://student.valuxapps.com/storage/uploads/products/1620253816SgPr3.1.jpg",
      "name": "Black Earloop Face Mask - 50 Pcs in box",
      "description": "Type : Fold-Flat Dust Masks\r\nBrand : ARW\r\nPackage thickness: 12.4 centimeters\r\nPackage weight in KGs238 grams\r\nColor Family : Multi Color\r\nSub Type : Dust Masks\r\nSterilized fabric\r\nHypoallergenic\r\nFilter",
      "images": [
        "https://student.valuxapps.com/storage/uploads/products/1620253816FGOZo.1.jpg"
      ],
      "in_favorites": false,
      "in_cart": false
    }
  ],
  "first_page_url": "https://student.valuxapps.com/api/categories/43?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://student.valuxapps.com/api/categories/43?page=1",
  "next_page_url": null,
  "path": "https://student.valuxapps.com/api/categories/43",
  "per_page": 35,
  "prev_page_url": null,
  "to": 4,
  "total": 4
}
*/

  int? currentPage;
  List<CategoryProductsDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  CategoryProductsData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  CategoryProductsData.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <CategoryProductsDataData>[];
      v.forEach((v) {
        arr0.add(CategoryProductsDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
}

class CategoryProducts {
/*
{
  "status": true,
  "message": null,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 66,
        "price": 39.99,
        "old_price": 39.99,
        "discount": 0,
        "image": "https://student.valuxapps.com/storage/uploads/products/1620253816SgPr3.1.jpg",
        "name": "Black Earloop Face Mask - 50 Pcs in box",
        "description": "Type : Fold-Flat Dust Masks\r\nBrand : ARW\r\nPackage thickness: 12.4 centimeters\r\nPackage weight in KGs238 grams\r\nColor Family : Multi Color\r\nSub Type : Dust Masks\r\nSterilized fabric\r\nHypoallergenic\r\nFilter",
        "images": [
          "https://student.valuxapps.com/storage/uploads/products/1620253816FGOZo.1.jpg"
        ],
        "in_favorites": false,
        "in_cart": false
      }
    ],
    "first_page_url": "https://student.valuxapps.com/api/categories/43?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://student.valuxapps.com/api/categories/43?page=1",
    "next_page_url": null,
    "path": "https://student.valuxapps.com/api/categories/43",
    "per_page": 35,
    "prev_page_url": null,
    "to": 4,
    "total": 4
  }
}
*/

  bool? status;
  String? message;
  CategoryProductsData? data;

  CategoryProducts({
    this.status,
    this.message,
    this.data,
  });
  CategoryProducts.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? CategoryProductsData.fromJson(json["data"]) : null;
  }

}
