///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FaqsDataData {
/*
{
  "id": 1,
  "question": "Question 1",
  "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}
*/

  int? id;
  String? question;
  String? answer;

  FaqsDataData({
    this.id,
    this.question,
    this.answer,
  });
  FaqsDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    question = json["question"]?.toString();
    answer = json["answer"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["question"] = question;
    data["answer"] = answer;
    return data;
  }
}

class FaqsData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "question": "Question 1",
      "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
    }
  ],
  "first_page_url": "https://student.valuxapps.com/api/faqs?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://student.valuxapps.com/api/faqs?page=1",
  "next_page_url": null,
  "path": "https://student.valuxapps.com/api/faqs",
  "per_page": 35,
  "prev_page_url": null,
  "to": 5,
  "total": 5
}
*/

  int? currentPage;
  List<FaqsDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  FaqsData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  FaqsData.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FaqsDataData>[];
      v.forEach((v) {
        arr0.add(FaqsDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class Faqs {
/*
{
  "status": true,
  "message": null,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 1,
        "question": "Question 1",
        "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
      }
    ],
    "first_page_url": "https://student.valuxapps.com/api/faqs?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://student.valuxapps.com/api/faqs?page=1",
    "next_page_url": null,
    "path": "https://student.valuxapps.com/api/faqs",
    "per_page": 35,
    "prev_page_url": null,
    "to": 5,
    "total": 5
  }
}
*/

  bool? status;
  String? message;
  FaqsData? data;

  Faqs({
    this.status,
    this.message,
    this.data,
  });
  Faqs.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? FaqsData.fromJson(json["data"]) : null;
  }

}
