///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductSearchDataData {
/*
{
  "id": 58,
  "price": 1083,
  "image": "https://student.valuxapps.com/storage/uploads/products/161545152160GOl.item_XXL_39275650_152762070.jpeg",
  "name": "أداة تمرين حديد كيتل بيل من ستارك، 24 كجم",
  "description": "العلامة التجارية: ستارك\r\nاللون: اسود\r\nالوزن: 24 كغ\r\nالفئة المستهدفة: للجنسين",
  "images": [
    "https://student.valuxapps.com/storage/uploads/products/16154515218VdQx.item_XXL_39275650_152762070.jpeg"
  ],
  "in_favorites": false,
  "in_cart": false
}
*/

  int? id;
  int? price;
  String? image;
  String? name;
  String? description;
  List<String?>? images;
  bool? inFavorites;
  bool? inCart;

  ProductSearchDataData({
    this.id,
    this.price,
    this.image,
    this.name,
    this.description,
    this.images,
    this.inFavorites,
    this.inCart,
  });
  ProductSearchDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    price = json["price"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    if (json["images"] != null) {
      final v = json["images"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
    inFavorites = json["in_favorites"];
    inCart = json["in_cart"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["price"] = price;
    data["image"] = image;
    data["name"] = name;
    data["description"] = description;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["images"] = arr0;
    }
    data["in_favorites"] = inFavorites;
    data["in_cart"] = inCart;
    return data;
  }
}

class ProductSearchData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 58,
      "price": 1083,
      "image": "https://student.valuxapps.com/storage/uploads/products/161545152160GOl.item_XXL_39275650_152762070.jpeg",
      "name": "أداة تمرين حديد كيتل بيل من ستارك، 24 كجم",
      "description": "العلامة التجارية: ستارك\r\nاللون: اسود\r\nالوزن: 24 كغ\r\nالفئة المستهدفة: للجنسين",
      "images": [
        "https://student.valuxapps.com/storage/uploads/products/16154515218VdQx.item_XXL_39275650_152762070.jpeg"
      ],
      "in_favorites": false,
      "in_cart": false
    }
  ],
  "first_page_url": "https://student.valuxapps.com/api/products/search?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://student.valuxapps.com/api/products/search?page=1",
  "next_page_url": null,
  "path": "https://student.valuxapps.com/api/products/search",
  "per_page": 35,
  "prev_page_url": null,
  "to": 27,
  "total": 27
}
*/

  int? currentPage;
  List<ProductSearchDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  ProductSearchData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  ProductSearchData.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <ProductSearchDataData>[];
      v.forEach((v) {
        arr0.add(ProductSearchDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
}

class ProductSearch {
/*
{
  "status": true,
  "message": null,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 58,
        "price": 1083,
        "image": "https://student.valuxapps.com/storage/uploads/products/161545152160GOl.item_XXL_39275650_152762070.jpeg",
        "name": "أداة تمرين حديد كيتل بيل من ستارك، 24 كجم",
        "description": "العلامة التجارية: ستارك\r\nاللون: اسود\r\nالوزن: 24 كغ\r\nالفئة المستهدفة: للجنسين",
        "images": [
          "https://student.valuxapps.com/storage/uploads/products/16154515218VdQx.item_XXL_39275650_152762070.jpeg"
        ],
        "in_favorites": false,
        "in_cart": false
      }
    ],
    "first_page_url": "https://student.valuxapps.com/api/products/search?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://student.valuxapps.com/api/products/search?page=1",
    "next_page_url": null,
    "path": "https://student.valuxapps.com/api/products/search",
    "per_page": 35,
    "prev_page_url": null,
    "to": 27,
    "total": 27
  }
}
*/

  bool? status;
  String? message;
  ProductSearchData? data;

  ProductSearch({
    this.status,
    this.message,
    this.data,
  });
  ProductSearch.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? ProductSearchData.fromJson(json["data"]) : null;
  }
}
